lsi: false
safe: true
source: https://rohan-bhowmik.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"